version: "3"
services:

    db:
        image: mysql
        container_name: symfony_db
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: symfony_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    maildev:
        image: maildev/maildev
        container_name: symfony_maildev
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
          - "8081:80"
        restart: always
        networks:
            - dev

    www:
        build: php
        container_name: symfony_www
        ports:
          - "8741:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ${LOCAL_PROJECT_ROOT}:/var/www/html
        restart: always
        networks:
            - dev

networks:
    dev:

volumes:
    db-data: